INSERT OR IGNORE INTO tags (slug, display_name) VALUES
  ('anime', 'Anime'),
  ('watercolor', 'Watercolor'),
  ('cinematic', 'Cinematic'),
  ('portrait', 'Portrait'),
  ('landscape', 'Landscape'),
  ('cyberpunk', 'Cyberpunk'),
  ('vintage', 'Vintage'),
  ('minimalist', 'Minimalist'),
  ('fantasy', 'Fantasy'),
  ('sketch', 'Sketch'),
  ('3d-render', '3D Render'),
  ('neon', 'Neon'),
  ('film-noir', 'Film Noir'),
  ('pop-art', 'Pop Art'),
  ('abstract', 'Abstract');
